__all__ = ["G1Point", "G2Point", "GT", "Scalar"]

class G1Point:
    def __new__(cls) -> G1Point: ...
    @staticmethod
    def identity() -> G1Point: ...
    def __add__(self, rhs: G1Point) -> G1Point: ...
    def __sub__(self, rhs: G1Point) -> G1Point: ...
    def __mul__(self, rhs: Scalar) -> G1Point: ...
    def __neg__(self) -> G1Point: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def is_in_subgroup(self) -> bool: ...
    def to_compressed_bytes(self) -> bytes: ...
    @staticmethod
    def from_compressed_bytes(bytes: bytes) -> G1Point: ...
    @staticmethod
    def from_compressed_bytes_unchecked(bytes: bytes) -> G1Point: ...
    def to_xy_bytes_be(self) -> bytes: ...
    def to_xy_bytes_le(self) -> bytes: ...
    @staticmethod
    def from_xy_bytes_be(bytes: bytes) -> G1Point: ...
    @staticmethod
    def from_xy_bytes_le(bytes: bytes) -> G1Point: ...
    @staticmethod
    def from_xy_bytes_unchecked_be(bytes: bytes) -> G1Point: ...
    @staticmethod
    def from_xy_bytes_unchecked_le(bytes: bytes) -> G1Point: ...
    @staticmethod
    def map_from_fp_be(fp_bytes: bytes) -> G1Point: ...
    @staticmethod
    def map_from_fp_le(fp_bytes: bytes) -> G1Point: ...
    @staticmethod
    def multiexp_unchecked(points: list[G1Point], scalars: list[Scalar]) -> G1Point: ...

class G2Point:
    def __new__(cls) -> G2Point: ...
    @staticmethod
    def identity() -> G2Point: ...
    def __add__(self, rhs: G2Point) -> G2Point: ...
    def __sub__(self, rhs: G2Point) -> G2Point: ...
    def __mul__(self, rhs: Scalar) -> G2Point: ...
    def __neg__(self) -> G2Point: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def is_in_subgroup(self) -> bool: ...
    def to_compressed_bytes(self) -> bytes: ...
    @staticmethod
    def from_compressed_bytes(bytes: bytes) -> G2Point: ...
    @staticmethod
    def from_compressed_bytes_unchecked(bytes: bytes) -> G2Point: ...
    def to_xy_bytes_be(self) -> bytes: ...
    def to_xy_bytes_le(self) -> bytes: ...
    @staticmethod
    def from_xy_bytes_be(bytes: bytes) -> G2Point: ...
    @staticmethod
    def from_xy_bytes_le(bytes: bytes) -> G2Point: ...
    @staticmethod
    def from_xy_bytes_unchecked_be(bytes: bytes) -> G2Point: ...
    @staticmethod
    def from_xy_bytes_unchecked_le(bytes: bytes) -> G2Point: ...
    @staticmethod
    def map_from_fp2_be(fp2_bytes: bytes) -> G2Point: ...
    @staticmethod
    def map_from_fp2_le(fp2_bytes: bytes) -> G2Point: ...
    @staticmethod
    def multiexp_unchecked(points: list[G2Point], scalars: list[Scalar]) -> G2Point: ...

class Scalar:
    def __new__(cls, integer: int) -> Scalar: ...
    def __add__(self, rhs: Scalar) -> Scalar: ...
    def __sub__(self, rhs: Scalar) -> Scalar: ...
    def __mul__(self, rhs: Scalar) -> Scalar: ...
    def __truediv__(self, rhs: Scalar) -> Scalar: ...
    def __neg__(self) -> Scalar: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __int__(self) -> int: ...
    def pow(self, exp: Scalar) -> Scalar: ...
    def square(self) -> Scalar: ...
    def inverse(self) -> Scalar: ...
    def is_zero(self) -> bool: ...
    def is_one(self) -> bool: ...
    def to_le_bytes(self) -> bytes: ...
    @staticmethod
    def from_le_bytes(bytes: bytes) -> Scalar: ...
    def to_be_bytes(self) -> bytes: ...
    @staticmethod
    def from_be_bytes(bytes: bytes) -> Scalar: ...

class GT:
    def __new__(cls) -> GT: ...
    @staticmethod
    def zero() -> GT: ...
    @staticmethod
    def one() -> GT: ...
    @staticmethod
    def multi_pairing(g1s: list[G1Point], g2s: list[G2Point]) -> GT: ...
    @staticmethod
    def pairing(g1: G1Point, g2: G2Point) -> GT: ...
    @staticmethod
    def pairing_check(g1s: list[G1Point], g2s: list[G2Point]) -> bool: ...
    def __add__(self, rhs: GT) -> GT: ...
    def __sub__(self, rhs: GT) -> GT: ...
    def __mul__(self, rhs: GT) -> GT: ...
    def __neg__(self) -> GT: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
